### ISSUE TITLE
Column with header mismatch exception

### ISSUE THREAD

**Issue by momcina08** [nietras/Sep#10]
Hi, is there any way to somehow make the code not break if the column missmatch with header exception is thrown after we invoke reader.MoveNext()? Or to set some parameters when reader is initialized  to maybe ignore the columns that have null values, something like that.
Also if we ignore the exception and continue, iterator doesn't go to next row and never exits the loop with reader.MoveNext(), it just keeps repeating the same row over and over again, only incrementing the ID value.

**Comment by nietras** [comment]
Currently Sep does not support if rows do not match header. Perhaps you can give details on the data you have and how you expect this to be working (which columns match which header column and so on) if it was supported (no promises). And yes, when exception occurs you cannot simply ignore it.

**Comment by momcina08** [comment]
Any updates on this question?

**Comment by nietras** [comment]
I'm working on a new release with a rewrite of some internals which should then make it possible to disable the ColCount check. No promises, but will probably take a few weeks to finish.

**Comment by momcina08** [comment]
It seems that error is thrown when the column has no value(empty) entered inside it, because i get this exception: "nietras.SeparatedValues.SepThrow.InvalidDataException_ColCountMismatch(Int32 colCount, Int32 rowIndex, String row, Int32 expectedColCount, String firstRow)" and message "Found 24 column(s) on row 70", and there should have been 31 columns.

**Comment by nietras** [comment]
@momcina08 I have published https://www.nuget.org/packages/Sep/0.2.0-preview.1 which is a preview with a new option `DisableColCountCheck`, set this to `true` and you should no longer get this exception. You then have to handle this case manually by checking col counts yourself. This also makes Sep about 25% faster at the low level parsing. Let me know how it works.

**Comment by momcina08** [comment]
Are those colums which are "missing" now going to have empty or null values?

**Comment by nietras** [comment]
No, they just can't be accessed. There is no way to know which column is
missing or not.

**Comment by nietras** [comment]
Please upgrade to 0.2.0-preview.3 https://www.nuget.org/packages/Sep/0.2.0-preview.3 as there was a left-over Debugger.Break in preview.1. This should be the last preview before proper 0.2.0 that should follow without code changes.
