### ISSUE TITLE
Specified argument was out of the range of valid values. at nietras.SeparatedValues.SepReader.ParseNewRows()

### ISSUE THREAD

**Issue by hbruun** [nietras/Sep#108]
@nietras first a compliment. This library is insanely fast!!!

I'm running into a problem parsing a comma separated CSV file with lots of double quoted strings with embedded double quotes. I get 143,651 rows into the file and then it crashes with the Specified argument was out of the range of valid values. at nietras.SeparatedValues.SepReader.ParseNewRows() error. The total row count in the file is around 650,000 and there are lots of columns.

I tried creating a small file with just the column header row and the block of rows -10 to +10 around the place where it crashes on the larger file. That doesn't crash.

I also experimented with the reader options. I found out that I can flip the setting for Unescaped and then it no longer crashes. That leaves me with another problem as I'm also using the SepWriter to write out a subset of that much larger input file. This subset becomes formatted differently with the Unescaped setting set to non-default value (most of my double quotes are now missing).

Since the tiny -10 to + 10 row test file didn't crash it is almost like some quote escape variable is running out of range after dealing with a ton of these column/cell values with lots of embedded quotes.

Here is code stripped down to the basics

            using (SepReader reader = Sep.New(',').Reader(o => o with { HasHeader = true, DisableColCountCheck = true }).FromFile(sFilename))
            {
               using (SepWriter writer = reader.Spec.Writer().ToFile(sListingFilename)) 
               {
                  foreach (SepReader.Row row in reader)
                  {
                     nLine++;

                     string sName = row["Name"].ToString();
                     if (sName.IndexOf("lookingfor", StringComparison.OrdinalIgnoreCase) >= 0)
                     {
                        using SepWriter.Row writeRow = writer.NewRow(row); 
                     }
                  }
               }
            }

**Comment by nietras** [comment]
@hbruun thanks and thank you for the detailed description. While this does give an idea about where and when this issue occurs, it will be very hard to find the exact cause without a reproducible example/test.

Taking a small snippet around where the issue occurs is probably not enough since Sep processes the file in chunks, and you likely need at least a multiple of such to try to reproduce. That is perhaps 128KB before issue depending on row lengths. Ideally I need some file that reproduces the issue that you can share. Consider replacing all not comma and double quotes with "a" in small file with issue so no info in it. And garbling col names. Then contents should be anonymous. 

At very least perhaps share full exception details incl stack trace.

**Comment by hbruun** [comment]
@nietras I placed a try/catch in the ParseNewRows() function and it is telling me that it is the colInfosSpan.Slice() line below that is getting the exception, but only in release build.

            if (_parsingRowColEndsOrInfosStartIndex > 0)
            {
                var intsPerColInfo = GetIntegersPerColInfo();
                var colInfosSpan = _colEndsOrColInfos.AsSpan();
                var length = (_parsingRowColCount + 1) * intsPerColInfo;
                **colInfosSpan.Slice(_parsingRowColEndsOrInfosStartIndex * intsPerColInfo, length)
                    .CopyTo(colInfosSpan.Slice(0, length));**
                _parsingRowColEndsOrInfosStartIndex = 0;
            }

**Comment by nietras** [comment]
Do you have full stack trace?

**Comment by nietras** [comment]
Thanks. Buffer sizes are different between debug/release so this may explain why release only. This can be changed. Puzzling... still need some way to reproduce it, also for adding unit test for it.

**Comment by hbruun** [comment]
Specified argument was out of the range of valid values.    at nietras.SeparatedValues.SepReader.ParseNewRows() in C:\TempJunk\Test\Sep-main\src\Sep\SepReader.cs:line 230

The line number is going to be slightly off now because it put in try/catch and then edited it back out.

**Comment by hbruun** [comment]
I tried direct message to you on X but said it wasn't enabled/allowed. If you send me an email to henrik32259 at hotmail then I'll send you link to csv file.

**Comment by nietras** [comment]
Can you provide details on your machine where this error occurs on? OS? CPU? x86? Avx2? AVX-512? Etc.?

**Comment by nietras** [comment]
I think I have managed to reproduce the bug with a unit test.
```
   System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

 Stack Trace: 
   SepReader.ParseNewRows() line 231
   SepReaderTest.SepReaderTest_ParsingRowColCountsStressTest() line 481
   RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by nietras** [comment]
0.4.3 should be available now, thanks for reporting the issue!

**Comment by hbruun** [comment]
@nietras thank you for looking into the problem and coming up with an update/fix so quickly.
