### ISSUE TITLE
Case Sensitivity on row[string]

### ISSUE THREAD

**Issue by Dreamwalker666** [nietras/Sep#111]
Hi, @nietras 

Been trying out the library and love it brilliant work.

One issue I have had was case of CSV file headers not matching the case when referencing the row key.

This isn't an issue on my test data but the files come from an external source and they can easily use the wrong case.  So would it be possible to have an option to match case insensitive for the lookup?

**Comment by Dreamwalker666** [comment]
I have done a little investigation and pushed a branch with a working change.   

One problem I did have I couldn't find a way to test SepHeader.Parse directly as using Sep.New() I couldn't see a way to set the reader options?

**Comment by nietras** [comment]
It sounded like I was not clearly defining what I meant to change, I've created a work-in-progress PR for adding the relevant option in #113. I need to add tests, though.

**Comment by Dreamwalker666** [comment]
Ah right got you.  

I knew the change wouldn't be accurate I did, as I don't know the code base at all.  I just wanted to do a little investigation work to help out.  Passing it in does make more sense and why I had an issue trying to test it.

**Comment by nietras** [comment]
0.4.5 should be available on nuget, thanks for filling the issue.
