### ISSUE TITLE
No async support

### ISSUE THREAD

**Issue by alex-jitbit** [nietras/Sep#114]
Hi @nietras thanks for the library

I was really excited to try it, however, it's not async compatible, because `Row` is a `ref struct`

```cs
foreach (SepReader.Row row in reader)
{
    await DoStuff(); //compiler error
}
```

Any workarounds? (other than "read everything into a huge buffer and do your thing")

**Comment by nietras** [comment]
This is intentional, as also covered in README. You need to extract what you need from Row before spawning any tasks in DoStuff, which need to capture state. Same reasons as for a Span.

**Comment by alex-jitbit** [comment]
@nietras Thanks for the reply. Can you point me to where it is mentioned in README? It's pretty lengthy and searching for "async" on that page brings nothing.

P.S. It's pretty hard to "extract what you need" when working with millions of rows :( Basically means I need to buffer everything.  Ok, thanks.

**Comment by nietras** [comment]
See https://github.com/nietras/Sep?tab=readme-ov-file#why-sepreader-is-not-ienumerable-and-linq-compatible

> millions of rows

Extract what you need *per* row. Without concrete example of what you want to do I cannot provide help. Feel free to show exactly what you are trying to do and why DoStuff is async and why in that case it wants to take Sep Row directly instead of parsed data from that row.

**Comment by alex-jitbit** [comment]
`DoStuff()` is `async` because it saves the data into the database. Or sends it to an external API. Or uses an GPU to train an ML-model. Etc. Etc.

All these calls are naturally async b/c they don't use the CPU, but send the data to external hardware (network card, GPU, usb-controller etc) and I don't want to keep the thread occupied while it simply waits for that request to finish its work.

This is a very common use-case when developing server apps (vs "a local CSV parser for desktop/GUI/mobile").

> why it wants to take Sep Row directly instead of parsed data from that row.

Even if `DoStuff()` is not doing anything with the row data, and is just a simple `Task.Delay`, it still won't compile.

So I guess the only way is to parse and buffer all the rows (in case I need to process ALL the rows, like save them to a database).

**Comment by alex-jitbit** [comment]
I believe I will be able to work this around using your `reader.Enumerate` helper, thanks for pointing me to that link

**Comment by nietras** [comment]
It doesn't seem like I can get my point through here, I get all thr things you say but they all depend on using Row directly in an async/await scenario. Which is the issue. You *can* use the `reader` instead as discussed in readme. In any case if you use Enumerate you are doing exactly what I suggested. Parsing Row to something else before async/await call. If I understand. 
```csharp
using var reader = Sep.Reader().FromText(text);
while (reader.MoveNext())
{
    var row = reader.Current;
}
```

**Comment by alex-jitbit** [comment]
Yes, that code was exactly what I wrote at first and here's the error:

```cs
using var reader = Sep.Reader().FromText(text);
while (reader.MoveNext())
{
    var row = reader.Current; //Error CS4012 Parameters or locals of type 'SepReader.Row' cannot be declared in async methods or async lambda expressions.
}
```

However, yes, I was able to overcome this using `Enumerate` with a lambda. Took me w hile to find it.

**Comment by nietras** [comment]
Added examples in README in #118
