### ISSUE TITLE
How to start read not standard csv file.

### ISSUE THREAD

**Issue by Diddlik** [nietras/Sep#141]
I have csv files that have the first 3-4 lines of technical information and only then comes the correct format in csv form with header and data.

Can I still use the package @nietras?

**Comment by nietras** [comment]
Not directly. This is not supported by Sep. You can always write a wrapper around a TextReader to handle this though. Let that handle skipping the first data.

**Comment by Diddlik** [comment]
I have not found in wiki that I can e.g. pass a stream to the reader, where I have e.g. skipped 4 lines.

**Comment by nietras** [comment]
wiki? perhaps you mean readme, the API listed at end shows all overloads. could be added to readme of course. :)

**Comment by Diddlik** [comment]
I mean readme, sorry ;) Thank you for quick response, I will try ;)
