### ISSUE TITLE
Implement IDataReader

### ISSUE THREAD

**Issue by sirWest** [nietras/Sep#147]
I have to use CsvHelper's CsvDataReader for now as Sep's reader doesn't implement IDataReader. This allows me to read ~3 million rows of csv with streaming into DataTable and use SqlBulkCopy to get my data into the database table without reading it all into memory first. I have tried to use Sep as a backbone for implementing IDataReader myself but seems that Sep is built much different and doesn't even allow to derive from it's sealed SepReader class. Is this at all possible to do or is it a lost cause? I could try to do it but not sure if I'd waste my time doing so. Maybe someone has done this and has a class like that to share? By princimple it would be very simple forward-only reading as it just reads in data and passes on to mssql table.

**Comment by nietras** [comment]
You can't inherit from SepReader nor would I recommend that, you should wrap a SepReader in your own SepDataReader : IDataReader. I don't have any experience with IDataReader so cannot say if there would be any issues related to that, but wouldn't think so. I appreciate trying out Sep, but why not use Sylvan it's plenty fast too?

**Comment by nietras** [comment]
Closing as stale and answered. :)

**Comment by sherman89** [comment]
@sirWest I think Sylvan CSV library implements `IDataReader` and the performance is also very good, you could maybe check that out.
