### ISSUE TITLE
How to parse whole object from csv having different column names?

### ISSUE THREAD

**Issue by SViradiya-MarutiTech** [nietras/Sep#15]
We have csv file with column name "PERSON_F_NAME", "PERSON_L_NAME","PERSON_AGE" etc. 

```csharp
public class Person{
public string FirstName {get;set;};
public string LastName {get;set;};
public int Age {get;set;}
}
```

this is just for one file. there are other files which have different column names and have associated class with different Column Name
I want to write Generic way so that it can map Csv to Object

**Comment by nietras** [comment]
Thanks for your interest and question. Sep doesn't support mapping CSV to types or objects, please take a look at CsvHelper for that. That said mapping this takes very few lines of code.
```csharp
using var reader = Sep.Reader().FromFile("persons.csv");
var persons = new List<Person>();
foreach (var row in reader)
{
   var person = new Person()
   {
       FirstName = row["PERSON_F_NAME"].ToString(),
       LastName = row["PERSON_L_NAME"].ToString(),
       Age = row["PERSON_AGE"].Parse<int>(),
   };
   persons.Add(person);
}
```
