### ISSUE TITLE
Is it possible to supply multiple separators?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [nietras/Sep#156]
Is it possible to supply multiple separators, like [Split](https://learn.microsoft.com/en-us/dotnet/api/system.string.split?view=net-8.0#system-string-split(system-char()-system-int32-system-stringsplitoptions)) does?

> Parameters
> 
> separator
>     [Char](https://learn.microsoft.com/en-us/dotnet/api/system.char?view=net-8.0)[] 
> 
> An array of characters that delimit the substrings in this string

**Comment by DaghanGuven** [comment]
If i understand your question correctly, yes it is.
```cs
string example = "one,two.three;four";
char[] separators = { ',', '.', ';' };
string[] result = example.Split(separators);

// result = ["one", "two", "three", "four"]
```

**Comment by A9G-Data-Droid** [comment]
@DaghanGuven That is what I am doing currently, that's what my link is to.

I'm asking if `Sep` can do this. There is an interface on `ReadOnlySpan<char>` called [SplitAny](https://learn.microsoft.com/en-us/dotnet/api/system.memoryextensions.splitany?view=net-8.0) that could be used.

However, the [Sep Object](https://github.com/nietras/Sep/blob/be51e293936078fa6c2ed27408ff33850c4cd6aa/src/Sep/Sep.cs) only appears to store a single `char`, with no overload for `char[]`

**Comment by nietras** [comment]
@A9G-Data-Droid thanks for trying out Sep and asking this question. Multiple separators is not supported no. Sep uses highly optimized code for parsing and having to support multiple separators would be a lot of work. Hence, I have no immediate plans to support this in Sep. If you only need basic parsing as supported by dotnet I would just use that. :)

**Comment by A9G-Data-Droid** [comment]
Thanks @nietras ! Sep is great and it has become the tool I reach for whenever I am handling delimited data sets. In this case I will continue to use my own solution involving `ReadOnlySpan<char>.SplitAny`

**Comment by nietras** [comment]
@A9G-Data-Droid thanks 🤗
