### ISSUE TITLE
Report all duplicate headers

### ISSUE THREAD

**Issue by viceroypenguin** [nietras/Sep#161]
Currently, when a file has duplicate headers, Sep fails when adding it to the dictionary at https://github.com/nietras/Sep/blob/main/src/Sep/SepReaderHeader.cs#L32. However, when exposing an error to users, it would be helpful to indicate all duplicate headers instead of just the first one.

Would you be open to a PR that throws an exception from Sep including all duplicate header information instead of a BCL exception from the `Dictionary<,>` on the first one?

CC: @nietras

**Comment by nietras** [comment]
@viceroypenguin thanks for reporting this issue, the code you pointed to was not actually used in the SepReader anymore due to unescaping so instead cleaned that up and have a proposed PR in #162, does the exception shown in tests there work for you? Any suggestions?
