### ISSUE TITLE
Equivalent capability as `CsvHelper`'ss `ClassMap` + `GetRecords<T>` combination?

### ISSUE THREAD

**Issue by julealgon** [nietras/Sep#165]
I checked the readme and this library seems interesting as a potential replacement for our usages of `CsvHelper` in the future, once we manage to upgrade our projects to .NET8+.

However, looking at examples, I could not find equivalent capability to `CsvHelper`'s `ClassMap` and `GetRecords` combo, which is something we use _extensively_ today.

I see there is support for the `IParseable` interfaces, but apparently only for specific raw column values and not for entire rows (which would be similar to what `ClassMap` provides)?

Is there a way to get similar capability as `CsvHelper`'s `ClassMap` without writing a lot of code manually? If so, could you please document how that is used either in the readme, a separate doc, or in a wiki? If not, what would you recommend in place of those `CsvHelper` abstractions?

@nietras

**Comment by nietras** [comment]
@julealgon hi, thanks for considering Sep and asking this question. I have expanded the README with #166 to answer, that is Sep does not have any support for object mapping or any plans for this. If you use ClassMap extensively this could sound like you do not actually gain much from the reflection based object mapping so perhaps revisit code and see how much you gain from that vs. using simply straightforward code. Of course if you avoid having to write thousands of lines of code then I can certainly understand this being a must have for your use case. Then consider if a custom source generator could be used :)

**Comment by julealgon** [comment]
Thank you for the quick response @nietras. The reflection constraint is completely understandable, especially with the library being AoT/trimming-compatible.

I don't anticipate playing around with your library in the _short_ term, but it is a strong possibility maybe in a year or so. At that point, I'll check back on this and see what we can do (on our side) to convert all the existing `ClassMap`-based usages of `CsvHelper` using a source generator.

The updated readme looks good to me. Will leave it up to you to close this since you might want to associate it with the merge of that PR.

**Comment by nietras** [comment]
Sounds good. :)
