### ISSUE TITLE
[Feature] Possibility to skip lines when reading CSV file

### ISSUE THREAD

**Issue by suchoss** [nietras/Sep#168]
Hello @nietras, 

first of all, thanks for Sep. It is really amazing.

I was just wondering if you can add one feature - **to skip lines**?

My usecase is to merge record data from several (about 10) big 300 MB - 2GB csv files. We are processing open data and one opendata provider is dumping their DB tables, so to get full record, I need to go through more csv file tables and join them together through their Id. 

My idea is to create in memory indexes first by reading all csv files and storing their keys and positions where `_currentRowLineNumberFrom` starts and `_currentRowLineNumberTo` ends. It would be stored in `Dictionary<string,(int from, int to)>`

Then go record from record in main csv file and everytime I need to join data I would first look into the index in my dictionary and then read specific line and merge data.

Many thanks

**Comment by nietras** [comment]
Thank you for using Sep and you comment :)

Skipping lines, requires finding lines, requires parsing csv, requires doing that sequentially and hence is same as just doing the actual read. Just foreach until you find the line number interested and do that sorted. This is not a feature that makes sense to implement in this library.
