### ISSUE TITLE
Suggestion: Implement a way to clear Sep's internal buffer

### ISSUE THREAD

**Issue by Camderman106** [nietras/Sep#170]
Hi @nietras 

This is a really cool library.  Full disclosure, I only have a few years of programming experience, so there might be a way to do this I just haven't identified.
As far as I can tell, Sep's internal buffer can't be cleared. This makes it impossible to seek through the file stream to a specific point in the file (whilst maintaining the header information etc).

I wish to be able to create maps of large files. E.g. a Dictionary<TKey, long> where the long is the raw byte offset into the file for the start of a row/record. I'm able to do this with csv helper as it uses a plain streamreader which we can seek through, and discard the buffered values. (this is helpful for indexing large files and doing random/out of order reads without having it all in memory). However the same trick doesn't work on Sep. 

As far as I can tell this is due to the array pool mechanism or some other internal buffer but I dont fully understand it. All i can see is that manually making the stream reader and then seeking on it and clearing the buffer data doesn't seem to work.

Would it be difficult to implement this feature? Just the raw ability to seek the underlying stream. I can manage the byte offsets externally.

**Comment by nietras** [comment]
@Camderman106 thanks for the praise and comment. Sep does read from source as `TextReader` in chunks and where there is no guarantee that any position of underlying `Stream` corresponds to any given row, and no clearing of buffer or similar would help with that. So this cannot be supported in all likelihood. It's part of what makes Sep fast.

I don't actually understand how you can do this with CsvHelper either, so if you still think relevant a code example would help.

**Comment by Camderman106** [comment]
Thanks for your response! @nietras 

I knew I had done this previously somewhere so I went and found the project where it happened. That project is proprietary but I have mocked up an example below. (sorry about the formatting being slightly broken)

After taking another look at the project I noticed that to seek into the file the second time I am actually initialising a new CsvReader(with headers disabled) from the underlying stream (after seeking it the correct start position). I am then using the headers (which I previously stored) to reconstruct the records to dictionaries as needed. Its a bit clunky but it works. And it permits random seeks in memory friendly way

In a Sep world this might actually work the same way. If I just reinitialise the SepReader with headers disabled after seeking to the correct place, and then access it using numeric indices rather than the header names? Would that work? 

using CsvHelper;
using CsvHelper.Configuration;
using System.Diagnostics;
using System.Globalization;
using System.Text;

namespace StreamSeekingDemo;

public class Demo
{
    public static void Main()
    {
        //Example data (GPT generated)
        string csvData = @"ID,Name,Age,Country,Salary" + Environment.NewLine
                + "1,John Doe,28,USA,50000" + Environment.NewLine
                + "2,Jane Smith,34,UK,60000" + Environment.NewLine
                + "3,Ahmed Khan,29,Pakistan,55000" + Environment.NewLine
                + "4,Li Wei,31,China,58000" + Environment.NewLine
                + "5,Maria Garcia,27,Spain,53000";

        string filename = "example.csv";

        File.WriteAllText(filename, csvData, new UTF8Encoding(true)); //To disk for replication

        //some function to build the offset indexes. An example is given below
        var index = BuildIndexBy(filename, ["ID"]);
        string[] Headers;
        {
            //read headers once globally
            using var fileStream = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.Read);
            using var streamReader = new StreamReader(fileStream, detectEncodingFromByteOrderMarks: true, bufferSize: 4096); //smaller buffer better for random seeks
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = true,
                IgnoreBlankLines = true,
                BadDataFound = null,

            };
            using var csvReader = new CsvReader(streamReader, config);
            csvReader.Read();
            csvReader.ReadHeader();
            Headers = csvReader.HeaderRecord!;
        }
        {
            //Read record 3
            using var fileStream = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.Read);
            using var streamReader = new StreamReader(fileStream, detectEncodingFromByteOrderMarks: true, bufferSize: 4096); //smaller buffer better for random seeks
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = false, //FALSE
                IgnoreBlankLines = true,
                BadDataFound = null,
            };
            //Seek to the third record
            var offset = index["3"];
            streamReader.BaseStream.Seek(offset, SeekOrigin.Begin);
            streamReader.DiscardBufferedData();

            using var csvReader = new CsvReader(streamReader, config);
            csvReader.Read();
            Dictionary<string, string> record3 = Enumerable.Range(0, Headers.Length).Select(x => new KeyValuePair<string, string>(Headers[x], csvReader.GetField(x)!)).ToDictionary();
            Debug.Assert(record3["Name"].ToString() == "Ahmed Khan");
        }
    }
    /// <summary>
    /// This function demonstrates one possible way to build the indexes for seeking through the file
    /// </summary>
    /// <param name="filename"></param>
    /// <param name="headersToIndexBy"></param>
    /// <returns></returns>
    private static Dictionary<string, long> BuildIndexBy(string filename, string[] headersToIndexBy)
    {
        Dictionary<string, long> offsets = new();

        //Note that the byte offsets will be affected by the presense of a BOM within the file, so we have to detect that
        Encoding encoding = new UTF8Encoding(false); //UTF8 without the BOM
        using var fileStream = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.Read);
        using var streamReader = new StreamReader(fileStream, detectEncodingFromByteOrderMarks: true);

        //Forces the BOM detection to happen. If a BOM is present the encoding used will change.
        //This ensures that the Encoding.Preamble.Length matches the BOM in the file, even if its missing from the file      
        streamReader.Peek();
        encoding = streamReader.CurrentEncoding; //overwrite with new encoding
        int BOM_Length = encoding.Preamble.Length;
        Debug.Assert(BOM_Length == 3); // for the utf8 BOM in this example

        //Now read through the file
        var config = new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = true,
            IgnoreBlankLines = true,
            BadDataFound = null, // Ignore bad data
            CountBytes = true, //This makes csv reader count the bytes for you, but you can also do this manually
        };
        using var csvReader = new CsvReader(streamReader, config);
        csvReader.Read();
        csvReader.ReadHeader();

        long byteOffset = csvReader.Parser.ByteCount + BOM_Length; // Position after reading header
        var ColumnHeaders = csvReader.HeaderRecord!.ToList();
        int[] ColumnIndexPositions = headersToIndexBy.Select(x => ColumnHeaders.IndexOf(x)).ToArray(); //Maybe validate no missing columns etc

        while (csvReader.Read())
        {
            var record = csvReader.GetRecord<dynamic>();
            string key = string.Join("|", ColumnIndexPositions.Select(x => csvReader.GetField(x) ?? string.Empty));
            offsets[key] = byteOffset; //will just overwrite existing entries for this demo
            byteOffset = csvReader.Parser.ByteCount + BOM_Length;
        }
        return offsets;
    }
}

**Comment by nietras** [comment]
Wow, that's a lot of code. I think I get the gist now, thank you. I think I can safely say Sep isn't a good fit for this, but I'd also say CsvHelper probably isn't either and that you should just parse this yourself, assuming you have firm constraints like source always UTF8, perhaps no quotes etc, and then be inspired by Daniel Lemire and his blog post 

[How fast can you parse a CSV file in C#?](https://lemire.me/blog/2024/10/17/how-fast-can-you-parse-a-csv-file-in-c/) 

and use the low-level parsing done there instead.

**Comment by Camderman106** [comment]
Thanks again for your response @nietras 

I took that idea in the meantime and implemented it and it worked! I understand it may indeed be faster to parse it myself, but I cannot trust that its always utf8 and there may be quotes in the data. Given all the nuances of csv parsing I'd rather use a tested parser for now. Even if this is a bit slower than optimal, its still probably a lot faster than what I could build myself. (Unless there is a lot of overhead in re-instantiating the SepReader for each random seek)

I may take another look at it in future though, so thank you for the link! And thanks again for this speedy library!

**Comment by nietras** [comment]
Yes, you can of course initialize a new reader from any point by a stream. This is likely going to be quite slow depending on the size of the rows you have, as Sep reads a large chunk on each read e. g. 32KB, so if one row only a few hundred chars this is going to be slow, compared to a manual approach.

If you store both the start and end offset for a row, all you have to do is seach for separator `, ` and quote `"` and handle that in a span for row, which is fairly easy, and would be much faster I think. Just a suggestion.

**Comment by Camderman106** [comment]
Hi again @nietras 

For my use case I found that it was adequate to modify Sep to make the buffer size configurable. I moved this code from the SepReader.cs to the SepReaderOptions.cs.  

SepReaderOptions.cs.  
```
#if DEBUG
    public int CharsMinimumLength { get; init; } = 64;
#else
    public int CharsMinimumLength { get; init; } = 1024 * 24;
#endif
```

And then in the SepReader i just made the CharsMinimumLength a normal field, an initialised it in the constructor. I had to fix one test to look this up from the new location, but the other tests pass.

I then made the buffer smaller for random row seeks, which I believe should avoid most of the performance bottleneck you described. Would you have any objection to this being configurable?
