### ISSUE TITLE
Question: Direct byte reading via byte sequences without decoder possible?

### ISSUE THREAD

**Issue by kikaragyozov** [nietras/Sep#174]
Greetings nietras! Exceptional library. Hands down the best one out there. The skills required to pull this off using vectornization is outstanding.

I'm facing a scenario where I need to split a CSV file into smaller valid CSV file chunks. The chunk size must be configurable and specified in bytes.

I've created a very aggressively optimized solution, which completely assumes the file being read is a CSV file. It does not use a StreamReader/Encoding/Decoder/Encoder. The only time it uses any of that, is to get the sequence of bytes for the important pieces to look for: a quote, CR and LF.

After that it's just a matter of simply reading bytes from the underlying stream and checking if we have a matching sequence for any of the 3 symbols.

Do you know if it's safe to do so? I've heard that certain encodings use multi-byte sequences, i.e the quote sequence may be contained in a a larger byte-sequence for example and I'd be required to use a decoder to decode every single character and do comparisons via chars? Alternatively, if we assume the encoding to only be UTF-8 - is my approach then valid, or it can still contain multi-byte sequences containing the control characters and the quote character?

I'm asking this because without a decoder, the performance increase is at minimum 2x, and only grows larger, the larger the chunk to split the file is. This is probably because I'm reading from the stream the chunk size, rather than using an internal, smaller buffer.

Benchmark results if interested involving the 2 approaches on a 450 MB csv file, with chunks sizes of 82kb. The tested code simply returns the start and end positions for each chunk - no actual I/O is being done to create the chunks.
![image](https://github.com/user-attachments/assets/2b6acc81-bdd8-4702-92a4-3ab080a419d6)

**Comment by nietras** [comment]
Hi @kikaragyozov! If I understand your question correctly I think this should be fine for UTF-8, which has been designed as shown below. Note how the single byte 1 is constrained to 0-127 and that this cannot occur in multi-byte code points. This of course assume you now for sure what the bytes actually are encoded as in the file.

https://en.wikipedia.org/wiki/UTF-8
![image](https://github.com/user-attachments/assets/906ea4da-bf70-489b-a375-822f0d251450)

**Comment by kikaragyozov** [comment]
Thank you! I'll be going down the route of using UTF-8. When I specialized it for UTF-8 only, I got a substantial performance gain - 500-600ms.
