### ISSUE TITLE
Proposal for a Seek() method to control the position of the underying stream

### ISSUE THREAD

**Issue by Camderman106** [nietras/Sep#178]
Thanks @nietras for adding in the initial buffer size option. I appreciate it!

In the original post (issue #170 ) I mentioned my specific use case which was to be able to perform random seeks throughout the stream in a performant way. Given that you have now made the buffer size configurable, I figured I might as well share the other modification I made for my use case. **(although I recognise that this functionality introduces possible row alignment issues, so you may wish to not support this)**

The proposal is a seek function that moves the underlying stream. I'm always initialising the SepReader from a StreamReader so this works for me, but you may want to generalise it and you will be more aware of any edge cases I haven't considered

### Offset
(SepReader.cs)
```
public void Seek(long offset)
{
    if (_reader is StreamReader streamReader && streamReader.BaseStream.CanSeek)
    {
        // Seek the base stream
        streamReader.BaseStream.Seek(offset, SeekOrigin.Begin);
        // Reset the StreamReader's internal buffer
        streamReader.DiscardBufferedData();
        // Reset parsing state
        _charsDataStart = 0;
        _charsDataEnd = 0;
        _charsParseStart = 0;
        _parsingRowCharsStartIndex = 0;
        _parsingRowColEndsOrInfosStartIndex = 0;
        _parsingRowColCount = 0;
        _parsedRowIndex = 0;
        _parsedRowsCount = 0;
        _currentRowColCount = -1;
        _currentRowColEndsOrInfosOffset = 0;
        _currentRowLineNumberFrom = 1;
        _currentRowLineNumberTo = 1;
        _rowIndex = -1;
        _parsingLineNumber = 1; // or set to the appropriate line number

        MoveNext();
    }
    else
    {
        throw new NotSupportedException("The underlying stream does not support seeking.");
    }
}
```

In my use case, I am using the following functions to build up the indexes. Although in theory Sep could expose the byte count from the parser if you wanted to go down that route

### Example offset map generation function (for reference)
```
internal IReadOnlyDictionary<StringArrayKey, long> CreateIndexByColumns(string[] columnHeadersToIndex)
{
    bool DetectedDuplicateKeys = false;
    Dictionary<StringArrayKey, long> RowPositions = new();
    using (var fs = new FileStream(FilePath, FileMode.Open, FileAccess.Read))
    {
        using (var reader = Sep.Auto.Reader(o => o with { HasHeader = true }).From(fs))
        {
            long offset = Encoding.GetPreamble().Length;
            offset += Encoding.GetByteCount(reader.Header.ToString()) + Encoding.GetByteCount(LineTerminator);
            while (reader.MoveNext())
            {
                SepReader.Row row = reader.Current;
                var indexCols = reader.Header.IndicesOf(columnHeadersToIndex);
                var indexValues = reader.Current[indexCols];
                var key = new StringArrayKey(indexValues.ToStringsArray());
                if (DetectedDuplicateKeys == false && RowPositions.ContainsKey(key))
                {
                    DetectedDuplicateKeys = true;
                    Console.WriteLine("Warning: Duplicate keys detected while indexing file. Earlier values will be overwritten");
                }
                RowPositions[key] = offset;
                offset += Encoding.GetByteCount(row.Span) + Encoding.GetByteCount(LineTerminator);
            }
        }
    }
    return RowPositions;
}
```

And i make sure that the seeking instance of the SepReader class is initialised with a small buffer, e.g. 1024 characters

**Comment by nietras** [comment]
Thanks again for a detailed proposal. :)

> so you may wish to not support this

You are right that I do not think this is within scope of something that I want to support with Sep. It still seems to me with all the code you have for your approach that you might be better off with both perf and amount of code by writing basic one row at a time parsing yourself. .NET primitives for this are pretty good in .NET 9 and all you have to track is pairs of quotes, which is not that hard.

Feel free to make other suggestions or re-open this issue if new thoughts.

**Comment by Camderman106** [comment]
Thanks neitras. 

I took your advice and tried to build my own parser. I've got something that seems to work, and yes it is faster than using Sep as I can keep the internal buffers much smaller. You were right!

However, I don't have a lot of confidence in my parser implementation. I can already see edge cases that it doesn't handle. And whilst I've tried to make it fast, I lack your expertise. I thought it would be a good idea to share it with you to see what you think, given that you clearly have experience with csv parsers. Any advice would be welcome.

If you're interested you can find the code here: 
https://github.com/Camderman106/Nemo/tree/master/Nemo/IO

Specifically you'll want to look at CsvRowStream and CsvRowParser.
If you also look at the Table class you'll get an idea for the kind of wrapper I originally wanted to build around Sep.
In the Example Model you can see some examples of how a consumer would use the Tables. It should make some sense. The primary use case is making lookups fast, rather than sequentially streaming files.
