### ISSUE TITLE
Namespace nietras.SeperatedValues does not conform to naming guidelines

### ISSUE THREAD

**Issue by summer600** [nietras/Sep#44]
@nietras
Not really an Issue but more a suggestion.  Namespace naming guidelines suggest using PascalCasing (https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces).  
You might also want to reserve the "Nietras" prefix on nuget and name the package with that name as well. So instead of "Sep" use "Nietras.Sep". Or remove the "nietras" namespace prefix from the source like some other packages do (such as Serilog) and then reserve "Sep" as prefix on nuget.

**Comment by nietras** [comment]
Sorry, I am well aware of the guidelines and have quite deliberately decided to use the names as they are. Guidelines are not rules. Being short is point of design for Sep. If I could have had namespace same I would have, but that has issues.
