### ISSUE TITLE
Assembly not StrongNamed signed

### ISSUE THREAD

**Issue by henriblMSFT** [nietras/Sep#66]
@nietras the Sep.dll assembly isn't strongly signed so it cannot be referenced by assembly that are strong name signed.

It looks like Sep's dependency csFastFloat isn't signed either.

**Comment by nietras** [comment]
@henriblMSFT you are right, and I don't really have any plans on strong name signing. And csFastFloat would have to be too. Open for contributions for it though, if it's not too cumbersome to maintain.

**Comment by AliveDevil** [comment]
With .NET 7 and .NET 8 as targeted and only runtimes available, strong naming isn't of any value.

> For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

[snip](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named)

**Comment by nietras** [comment]
Closing as of no consequence. 👍
