### ISSUE TITLE
Implement SepWriterOptions.WriteHeader (false)

### ISSUE THREAD

**Issue by nietras** [nietras/Sep#71]
Currently `SepWriter` does not support writing **without** a header implement this via new option `WriteHeader`. Default true.

 * Add `SepWriterOptions.WriteHeader`
 * Allow adding rows by col index e.g. if index is +1 from last index add column.
 * Still allow named columns, but fail if trying to access a column by name if column only added by index.

**Comment by JoshZA** [comment]
👍 We need this to implement mutlithreaded appends to files

**Comment by pedro-de-rycker-sncf** [comment]
I am really interested by this feature also :-)

**Comment by pedro-de-rycker** [comment]
And that reactivity my good sir is really a nice thing !
Thanks for the release :-)

**Comment by nietras** [comment]
Thanks, 0.4.2 should be on nuget now.
