### ISSUE TITLE
Add support for skipping empty lines?

### ISSUE THREAD

**Issue by kikaragyozov** [nietras/Sep#84]
Is it possible to add support to the parser that skips empty lines? They should still be counted when reporting issues such as an `InvalidDataException`.

Tagging @nietras for notification as instructed.

**Comment by nietras** [comment]
There is no built in support for this and the design philosophy is not to have such keeping sep minimal. Instead, you have do a bit of work yourself which I have given an example for in #87 and now available in README. Thank you for reporting your issue and using Sep.

**Comment by kikaragyozov** [comment]
Thank you for addressing this @nietras! May I ask if there's an easy way to have this working with `DisableColCountCheck` set to `false`? I went ahead and looked at the source code to potentially apply a local patch for my own use-case, but like any new project, especially high-performance once that use vectorization, I'm a bit loss at the best place to inject it.

Alternatively I might just use the public API as-is, and do what `DisableColCountCheck` does manually, that is - store the number of rows read in the first line, and if there ever is a miss-match - throw an exception.

**Comment by nietras** [comment]
> Alternatively I might just use the public API as-is, and do what DisableColCountCheck does manually, that is - store the number of rows (edit: **cols**) read in the first line (edit: row), and if there ever is a miss-match - throw an exception.

I think that is your best choice, it is not that materially different from what Sep does internally anyway. And simple to do. I could expand the README example to cover it if necessary.

**Comment by kikaragyozov** [comment]
> > Alternatively I might just use the public API as-is, and do what DisableColCountCheck does manually, that is - store the number of rows (edit: **cols**) read in the first line (edit: row), and if there ever is a miss-match - throw an exception.
> 
> I think that is your best choice, it is not that materially different from what Sep does internally anyway. And simple to do. I could expand the README example to cover it if necessary.

Expanding the README won't be necessary. Thanks again!
