### ISSUE TITLE
Add support for trimming quoted csv headers and values?

### ISSUE THREAD

**Issue by marc-weber1** [nietras/Sep#85]
Currently, trying to parse a CSV with quotes expands this:
`DateTime current_start_time = csv_reader.Current["Time Stamp"].Parse<DateTime>();`
All the way out to this:
`DateTime current_start_time = DateTime.Parse(csv_reader.Current["\"Time Stamp\""].ToString().Trim('"'));`
Maybe there's a better or more optimized way to trim headers and values in-place before parsing? The main problem with the solution above is that a CSV with no quotes around the Time Stamp column in the header row would not be parsed correctly.

**Comment by marc-weber1** [comment]
might be a duplicate of https://github.com/nietras/Sep/issues/74 - my bad

**Comment by nietras** [comment]
Removing quotes is called "unescaping" and is already supported as detailed in README https://github.com/nietras/Sep?tab=readme-ov-file#unescaping with Unescape option. Trimming e.g. of spaces is not yet supported and covered in #74 as you mention, but that is a different thing.
