### ISSUE TITLE
Question about batch write

### ISSUE THREAD

**Issue by hs41-18** [nietras/Sep#86]
Hi, first of all, thank you very much for the work that does an excellent job. 

I am trying to write down around 600M rows into Csv. Have tried several options but couldn't find the sweet spot between batch insert and single line per time. What would be your suggestion on where to focus? 

Essentially a bunch of work to get into the `array`
and then. 
```
 using var row = writer.NewRow();
        for (int i = 0; i < array.Length; i++)
        {
            row[i.ToString()].Format(array[i]);
        }
```
`array` is always a long number

**Comment by nietras** [comment]
calling `i.ToString()` on every row will be very slow as it allocates a string each time, avoid this. simplest right now is probably to define the first row differently from the rest so:
```csharp
// First row
using var firstRow = writer.NewRow();
for (int i = 0; i < array.Length; i++)
{
    firstRow[i.ToString()].Format(array[i]);
}
for (....) // Iterate over remaining rows
{
    using var row = writer.NewRow();
    for (int i = 0; i < array.Length; i++)
    {
        row[i].Format(array[i]);
    }
}
```

**Comment by hs41-18** [comment]
thanks @nietras, indeed I overlooked it. It does save another 9-10 seconds. Writing 571536000 rows (each with 6x int/long) takes 131s on average. From your experience, is it an acceptable performance or can it be better? 

I'm on m1, ssd write speed seems to be around 3.5gb/s. Output CSV is around 13gb.
