### ISSUE TITLE
Ignore double quotes in data

### ISSUE THREAD

**Issue by grsgrs** [nietras/Sep#91]
Hi @nietras 
is it possible to ignore double quotes in data, I have a csv line ( delimiter is ,):
0237,02,0000021594,000833738000041,RCSM-B1"/65,0008337380000,2022-11-01 00:30:16

and this line results in this exception:
Buffer or row has reached maximum supported length of 16777216. If no such row should exist ensure quotes " are terminated.

Thanks
grsgrs

**Comment by nietras** [comment]
@grsgrs not at the moment no. Will have to look at how to disable quotes parsing without impacting existing perf and without causing code balooning.

**Comment by nietras** [comment]
#115 fixes this.

**Comment by nietras** [comment]
Fixed with #115
