### ISSUE TITLE
Option to leave stream open after writing

### ISSUE THREAD

**Issue by chrislewisdev** [nietras/Sep#97]
Hello @nietras and thanks for this library!

It appears there is no option to leave a stream open after writing to it with `SepWriter`, would it be feasible to add one?

My use case: I am processing a file, applying some transformations to certain column values, which will then be sent off to another API. So I am writing into a `MemoryStream` which will be attached to the API call as file content.

Without an option to leave the stream open, my options are to either not Dispose the `SepWriter` (which I assume may leave some internal objects undisposed), or create a new copy of the `MemoryStream` that I can then re-use (which involves copying the whole file over in memory again).

**Comment by nietras** [comment]
If you create a StreamWriter over MemoryStream yourself and set leaveOpen to true, then I would think this works for you. Correct?

It very well may be that there should be easier support for this with an overload, but it can quickly end up in overload hell. 😅

**Comment by chrislewisdev** [comment]
Ahh thanks for the suggestion, that actually does work! I had just assumed that the writer on the Sep end must have been doing something to close the stream, so I didn't realise I could circumvent the behaviour like this :)

**Comment by nietras** [comment]
Added convenience overloads with `leaveOpen` for this in the future in #123
